In [1]:
import numpy as np
import pandas as pd

In [2]:
dict1 = {
    "Name" : ['Avinno', 'Avash', 'Nirob', 'Nasif'],
    "Marks" : [92, 87, 73, 81],
    "City" : ['Jhenaidah', 'Jessore', 'Khulna', 'Kushtia']

}

In [3]:
df = pd.DataFrame(dict1)

In [4]:
df

     Name  Marks       City
0  Avinno     92  Jhenaidah
1   Avash     87    Jessore
2   Nirob     73     Khulna
3   Nasif     81    Kushtia

In [5]:
df.to_csv('Info.csv')

In [6]:
df.to_csv('Info_indexfalse.csv', index=False)

In [7]:
df.head(2)

     Name  Marks       City
0  Avinno     92  Jhenaidah
1   Avash     87    Jessore

In [8]:
df.tail(2)

    Name  Marks     City
2  Nirob     73   Khulna
3  Nasif     81  Kushtia

In [9]:
df.describe()

           Marks
count   4.000000
mean   83.250000
std     8.180261
min    73.000000
25%    79.000000
50%    84.000000
75%    88.250000
max    92.000000

In [10]:
avash = pd.read_csv('avash_csv.csv')

In [11]:
avash

   Unnamed: 0  Train No  Speed        City
0           0      1122     57     Jessore
1           1      2233     34      Khulna
2           2      3443     45  Chittagong
3           3      1414     51       Dhaka

In [12]:
avash['Speed']

0    57
1    34
2    45
3    51
Name: Speed, dtype: int64

In [13]:
avash['Speed'][0] = 57

C:\Users\HP\AppData\Local\Temp\ipykernel_868\742755349.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  avash['Speed'][0] = 57

In [14]:
avash['Speed']

0    57
1    34
2    45
3    51
Name: Speed, dtype: int64

In [15]:
avash.index= ['1st', '2nd', '3rd', '4th']

In [16]:
avash

     Unnamed: 0  Train No  Speed        City
1st           0      1122     57     Jessore
2nd           1      2233     34      Khulna
3rd           2      3443     45  Chittagong
4th           3      1414     51       Dhaka

In [17]:
sr = pd.Series(np.random.rand(10))

In [18]:
sr

0    0.306917
1    0.923706
2    0.212036
3    0.464674
4    0.825316
5    0.823292
6    0.195090
7    0.001385
8    0.306719
9    0.298857
dtype: float64

In [19]:
type(sr)

pandas.core.series.Series

In [20]:
newdf = pd.DataFrame(np.random.rand(334,5), index = np.arange(334))

In [21]:
newdf

            0         1         2         3         4
0    0.184930  0.135993  0.451597  0.546875  0.892992
1    0.793664  0.056516  0.881566  0.529042  0.725634
2    0.278231  0.345458  0.881023  0.960155  0.150347
3    0.187675  0.515800  0.352888  0.682026  0.644596
4    0.082039  0.804506  0.447780  0.305676  0.033966
..        ...       ...       ...       ...       ...
329  0.920143  0.348268  0.512512  0.546789  0.084023
330  0.217604  0.854548  0.317432  0.124896  0.048972
331  0.713451  0.520955  0.116990  0.939516  0.253913
332  0.755872  0.730676  0.107655  0.209220  0.586807
333  0.100367  0.141618  0.557154  0.581961  0.537607

[334 rows x 5 columns]

In [22]:
type(newdf)

pandas.core.frame.DataFrame

In [23]:
newdf.describe()

                0           1           2           3           4
count  334.000000  334.000000  334.000000  334.000000  334.000000
mean     0.468059    0.520036    0.485936    0.505613    0.475682
std      0.294609    0.294578    0.296181    0.284094    0.283320
min      0.004040    0.000135    0.001955    0.000236    0.003047
25%      0.194665    0.247309    0.226028    0.273646    0.222962
50%      0.470008    0.556609    0.470346    0.493824    0.474482
75%      0.745318    0.782967    0.733466    0.761307    0.709463
max      0.993711    0.991643    0.999320    0.999521    0.997700

In [24]:
newdf.head()

          0         1         2         3         4
0  0.184930  0.135993  0.451597  0.546875  0.892992
1  0.793664  0.056516  0.881566  0.529042  0.725634
2  0.278231  0.345458  0.881023  0.960155  0.150347
3  0.187675  0.515800  0.352888  0.682026  0.644596
4  0.082039  0.804506  0.447780  0.305676  0.033966

In [25]:
newdf.dtypes

0    float64
1    float64
2    float64
3    float64
4    float64
dtype: object

In [26]:
newdf[0][0] = 'avash'

C:\Users\HP\AppData\Local\Temp\ipykernel_868\2553957607.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  newdf[0][0] = 'avash'
C:\Users\HP\AppData\Local\Temp\ipykernel_868\2553957607.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'avash' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  newdf[0][0] = 'avash'

In [27]:
newdf

            0         1         2         3         4
0       avash  0.135993  0.451597  0.546875  0.892992
1    0.793664  0.056516  0.881566  0.529042  0.725634
2    0.278231  0.345458  0.881023  0.960155  0.150347
3    0.187675  0.515800  0.352888  0.682026  0.644596
4    0.082039  0.804506  0.447780  0.305676  0.033966
..        ...       ...       ...       ...       ...
329  0.920143  0.348268  0.512512  0.546789  0.084023
330  0.217604  0.854548  0.317432  0.124896  0.048972
331  0.713451  0.520955  0.116990  0.939516  0.253913
332  0.755872  0.730676  0.107655  0.209220  0.586807
333  0.100367  0.141618  0.557154  0.581961  0.537607

[334 rows x 5 columns]

In [28]:
newdf.dtypes

0     object
1    float64
2    float64
3    float64
4    float64
dtype: object

In [29]:
newdf.head()

          0         1         2         3         4
0     avash  0.135993  0.451597  0.546875  0.892992
1  0.793664  0.056516  0.881566  0.529042  0.725634
2  0.278231  0.345458  0.881023  0.960155  0.150347
3  0.187675  0.515800  0.352888  0.682026  0.644596
4  0.082039  0.804506  0.447780  0.305676  0.033966

In [30]:
newdf.index

Index([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,
       ...
       324, 325, 326, 327, 328, 329, 330, 331, 332, 333],
      dtype='int64', length=334)

In [31]:
newdf.columns

RangeIndex(start=0, stop=5, step=1)

In [32]:
newdf.to_numpy()

array([['avash', 0.13599338626082502, 0.45159670320138723,
        0.546874827555372, 0.8929922235033965],
       [0.793663671230305, 0.056516196961230225, 0.8815656100901899,
        0.5290420121965344, 0.7256343795563402],
       [0.27823130912568694, 0.34545757253098275, 0.8810229658762507,
        0.960155303466193, 0.15034669137681111],
       ...,
       [0.7134514219360872, 0.5209548327537253, 0.11698987165427921,
        0.9395156876114598, 0.2539130880906204],
       [0.7558722296068686, 0.7306755017852123, 0.10765542746689327,
        0.20922012369556142, 0.5868071424685073],
       [0.10036712166148587, 0.14161774196266397, 0.5571544355028412,
        0.5819609102964066, 0.5376072432646756]],
      shape=(334, 5), dtype=object)

In [33]:
newdf.T

,0,1,2,3,4,5,6,7,8,9,...,324,325,326,327,328,329,330,331,332,333
0,avash,0.793664,0.278231,0.187675,0.082039,0.574246,0.403378,0.787283,0.231589,0.290345,...,0.257235,0.713413,0.733776,0.488695,0.799392,0.920143,0.217604,0.713451,0.755872,0.100367
1,0.135993,0.056516,0.345458,0.5158,0.804506,0.394258,0.117887,0.428423,0.411563,0.909669,...,0.908588,0.280509,0.304431,0.587498,0.699481,0.348268,0.854548,0.520955,0.730676,0.141618
2,0.451597,0.881566,0.881023,0.352888,0.44778,0.335982,0.784999,0.040054,0.597073,0.427889,...,0.10801,0.312763,0.319519,0.258303,0.663886,0.512512,0.317432,0.11699,0.107655,0.557154
3,0.546875,0.529042,0.960155,0.682026,0.305676,0.995672,0.805667,0.157303,0.809609,0.689933,...,0.800158,0.797097,0.402567,0.165388,0.916064,0.546789,0.124896,0.939516,0.20922,0.581961
4,0.892992,0.725634,0.150347,0.644596,0.033966,0.499268,0.590155,0.615342,0.630925,0.474808,...,0.081514,0.452699,0.468534,0.335938,0.212348,0.084023,0.048972,0.253913,0.586807,0.537607

In [34]:
newdf

            0         1         2         3         4
0       avash  0.135993  0.451597  0.546875  0.892992
1    0.793664  0.056516  0.881566  0.529042  0.725634
2    0.278231  0.345458  0.881023  0.960155  0.150347
3    0.187675  0.515800  0.352888  0.682026  0.644596
4    0.082039  0.804506  0.447780  0.305676  0.033966
..        ...       ...       ...       ...       ...
329  0.920143  0.348268  0.512512  0.546789  0.084023
330  0.217604  0.854548  0.317432  0.124896  0.048972
331  0.713451  0.520955  0.116990  0.939516  0.253913
332  0.755872  0.730676  0.107655  0.209220  0.586807
333  0.100367  0.141618  0.557154  0.581961  0.537607

[334 rows x 5 columns]

In [35]:
newdf.sort_index(axis=0, ascending=False)

            0         1         2         3         4
333  0.100367  0.141618  0.557154  0.581961  0.537607
332  0.755872  0.730676  0.107655  0.209220  0.586807
331  0.713451  0.520955  0.116990  0.939516  0.253913
330  0.217604  0.854548  0.317432  0.124896  0.048972
329  0.920143  0.348268  0.512512  0.546789  0.084023
..        ...       ...       ...       ...       ...
4    0.082039  0.804506  0.447780  0.305676  0.033966
3    0.187675  0.515800  0.352888  0.682026  0.644596
2    0.278231  0.345458  0.881023  0.960155  0.150347
1    0.793664  0.056516  0.881566  0.529042  0.725634
0       avash  0.135993  0.451597  0.546875  0.892992

[334 rows x 5 columns]

In [36]:
newdf.head()

          0         1         2         3         4
0     avash  0.135993  0.451597  0.546875  0.892992
1  0.793664  0.056516  0.881566  0.529042  0.725634
2  0.278231  0.345458  0.881023  0.960155  0.150347
3  0.187675  0.515800  0.352888  0.682026  0.644596
4  0.082039  0.804506  0.447780  0.305676  0.033966

In [37]:
newdf2 = newdf

In [38]:
newdf2

            0         1         2         3         4
0       avash  0.135993  0.451597  0.546875  0.892992
1    0.793664  0.056516  0.881566  0.529042  0.725634
2    0.278231  0.345458  0.881023  0.960155  0.150347
3    0.187675  0.515800  0.352888  0.682026  0.644596
4    0.082039  0.804506  0.447780  0.305676  0.033966
..        ...       ...       ...       ...       ...
329  0.920143  0.348268  0.512512  0.546789  0.084023
330  0.217604  0.854548  0.317432  0.124896  0.048972
331  0.713451  0.520955  0.116990  0.939516  0.253913
332  0.755872  0.730676  0.107655  0.209220  0.586807
333  0.100367  0.141618  0.557154  0.581961  0.537607

[334 rows x 5 columns]

In [39]:
newdf2[0][0] = 7878

In [40]:
newdf2

            0         1         2         3         4
0        7878  0.135993  0.451597  0.546875  0.892992
1    0.793664  0.056516  0.881566  0.529042  0.725634
2    0.278231  0.345458  0.881023  0.960155  0.150347
3    0.187675  0.515800  0.352888  0.682026  0.644596
4    0.082039  0.804506  0.447780  0.305676  0.033966
..        ...       ...       ...       ...       ...
329  0.920143  0.348268  0.512512  0.546789  0.084023
330  0.217604  0.854548  0.317432  0.124896  0.048972
331  0.713451  0.520955  0.116990  0.939516  0.253913
332  0.755872  0.730676  0.107655  0.209220  0.586807
333  0.100367  0.141618  0.557154  0.581961  0.537607

[334 rows x 5 columns]

In [41]:
newdf[0]

0          7878
1      0.793664
2      0.278231
3      0.187675
4      0.082039
         ...
329    0.920143
330    0.217604
331    0.713451
332    0.755872
333    0.100367
Name: 0, Length: 334, dtype: object

In [42]:
type(newdf[0])

pandas.core.series.Series

In [43]:
newdf2 = newdf.copy()

In [44]:
newdf2[0][0] = 78786

C:\Users\HP\AppData\Local\Temp\ipykernel_868\3428185774.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  newdf2[0][0] = 78786
C:\Users\HP\AppData\Local\Temp\ipykernel_868\3428185774.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  newdf2[0][0] = 78786

In [45]:
newdf2

            0         1         2         3         4
0       78786  0.135993  0.451597  0.546875  0.892992
1    0.793664  0.056516  0.881566  0.529042  0.725634
2    0.278231  0.345458  0.881023  0.960155  0.150347
3    0.187675  0.515800  0.352888  0.682026  0.644596
4    0.082039  0.804506  0.447780  0.305676  0.033966
..        ...       ...       ...       ...       ...
329  0.920143  0.348268  0.512512  0.546789  0.084023
330  0.217604  0.854548  0.317432  0.124896  0.048972
331  0.713451  0.520955  0.116990  0.939516  0.253913
332  0.755872  0.730676  0.107655  0.209220  0.586807
333  0.100367  0.141618  0.557154  0.581961  0.537607

[334 rows x 5 columns]

In [46]:
newdf.loc[0,0]= 56

In [47]:
newdf.head(2)

          0         1         2         3         4
0        56  0.135993  0.451597  0.546875  0.892992
1  0.793664  0.056516  0.881566  0.529042  0.725634

In [48]:
newdf.columns = list("ABCDE")

In [49]:
newdf.head(2)

          A         B         C         D         E
0        56  0.135993  0.451597  0.546875  0.892992
1  0.793664  0.056516  0.881566  0.529042  0.725634

In [50]:
newdf.loc[0,'A'] = 576

In [51]:
newdf

            A         B         C         D         E
0         576  0.135993  0.451597  0.546875  0.892992
1    0.793664  0.056516  0.881566  0.529042  0.725634
2    0.278231  0.345458  0.881023  0.960155  0.150347
3    0.187675  0.515800  0.352888  0.682026  0.644596
4    0.082039  0.804506  0.447780  0.305676  0.033966
..        ...       ...       ...       ...       ...
329  0.920143  0.348268  0.512512  0.546789  0.084023
330  0.217604  0.854548  0.317432  0.124896  0.048972
331  0.713451  0.520955  0.116990  0.939516  0.253913
332  0.755872  0.730676  0.107655  0.209220  0.586807
333  0.100367  0.141618  0.557154  0.581961  0.537607

[334 rows x 5 columns]

In [52]:
newdf.drop('E', axis=1)

            A         B         C         D
0         576  0.135993  0.451597  0.546875
1    0.793664  0.056516  0.881566  0.529042
2    0.278231  0.345458  0.881023  0.960155
3    0.187675  0.515800  0.352888  0.682026
4    0.082039  0.804506  0.447780  0.305676
..        ...       ...       ...       ...
329  0.920143  0.348268  0.512512  0.546789
330  0.217604  0.854548  0.317432  0.124896
331  0.713451  0.520955  0.116990  0.939516
332  0.755872  0.730676  0.107655  0.209220
333  0.100367  0.141618  0.557154  0.581961

[334 rows x 4 columns]

In [53]:
newdf

            A         B         C         D         E
0         576  0.135993  0.451597  0.546875  0.892992
1    0.793664  0.056516  0.881566  0.529042  0.725634
2    0.278231  0.345458  0.881023  0.960155  0.150347
3    0.187675  0.515800  0.352888  0.682026  0.644596
4    0.082039  0.804506  0.447780  0.305676  0.033966
..        ...       ...       ...       ...       ...
329  0.920143  0.348268  0.512512  0.546789  0.084023
330  0.217604  0.854548  0.317432  0.124896  0.048972
331  0.713451  0.520955  0.116990  0.939516  0.253913
332  0.755872  0.730676  0.107655  0.209220  0.586807
333  0.100367  0.141618  0.557154  0.581961  0.537607

[334 rows x 5 columns]

In [54]:
newdf.loc[[1,2], ['C', 'D']]

          C         D
1  0.881566  0.529042
2  0.881023  0.960155

In [55]:
newdf.head()

          A         B         C         D         E
0       576  0.135993  0.451597  0.546875  0.892992
1  0.793664  0.056516  0.881566  0.529042  0.725634
2  0.278231  0.345458  0.881023  0.960155  0.150347
3  0.187675  0.515800  0.352888  0.682026  0.644596
4  0.082039  0.804506  0.447780  0.305676  0.033966

In [56]:
newdf.loc[:, ['C', 'D']]

            C         D
0    0.451597  0.546875
1    0.881566  0.529042
2    0.881023  0.960155
3    0.352888  0.682026
4    0.447780  0.305676
..        ...       ...
329  0.512512  0.546789
330  0.317432  0.124896
331  0.116990  0.939516
332  0.107655  0.209220
333  0.557154  0.581961

[334 rows x 2 columns]

In [57]:
newdf.loc[[1,2], :]

          A         B         C         D         E
1  0.793664  0.056516  0.881566  0.529042  0.725634
2  0.278231  0.345458  0.881023  0.960155  0.150347

In [58]:
newdf.loc[(newdf['A'] < 0.3) & (newdf['D'] > 0.5)]

            A         B         C         D         E
2    0.278231  0.345458  0.881023  0.960155  0.150347
3    0.187675  0.515800  0.352888  0.682026  0.644596
8    0.231589  0.411563  0.597073  0.809609  0.630925
9    0.290345  0.909669  0.427889  0.689933  0.474808
13    0.19653  0.438854  0.210999  0.902821  0.706103
..        ...       ...       ...       ...       ...
318  0.173587  0.563773  0.622311  0.818263  0.019726
320  0.266983  0.602954  0.528247  0.830553  0.518744
323  0.162064  0.153759  0.773536  0.991206  0.962692
324  0.257235  0.908588  0.108010  0.800158  0.081514
333  0.100367  0.141618  0.557154  0.581961  0.537607

[62 rows x 5 columns]

In [59]:
newdf.head(3)

          A         B         C         D         E
0       576  0.135993  0.451597  0.546875  0.892992
1  0.793664  0.056516  0.881566  0.529042  0.725634
2  0.278231  0.345458  0.881023  0.960155  0.150347

In [60]:
newdf.iloc[0,4]

np.float64(0.8929922235033965)

In [61]:
newdf.head(3)

          A         B         C         D         E
0       576  0.135993  0.451597  0.546875  0.892992
1  0.793664  0.056516  0.881566  0.529042  0.725634
2  0.278231  0.345458  0.881023  0.960155  0.150347

In [62]:
newdf.iloc[[0,4], [2,3]]

          C         D
0  0.451597  0.546875
4  0.447780  0.305676

In [63]:
newdf.head(3)

          A         B         C         D         E
0       576  0.135993  0.451597  0.546875  0.892992
1  0.793664  0.056516  0.881566  0.529042  0.725634
2  0.278231  0.345458  0.881023  0.960155  0.150347

In [64]:
newdf.drop(['E', 'A'], axis=1, inplace=True)

In [65]:
newdf.head(3)

          B         C         D
0  0.135993  0.451597  0.546875
1  0.056516  0.881566  0.529042
2  0.345458  0.881023  0.960155

In [66]:
newdf.reset_index(drop=True, inplace=True)

In [67]:
newdf.head(3)

          B         C         D
0  0.135993  0.451597  0.546875
1  0.056516  0.881566  0.529042
2  0.345458  0.881023  0.960155

In [68]:
newdf['B'].isnull()

0      False
1      False
2      False
3      False
4      False
       ...
329    False
330    False
331    False
332    False
333    False
Name: B, Length: 334, dtype: bool

In [69]:
newdf

            B         C         D
0    0.135993  0.451597  0.546875
1    0.056516  0.881566  0.529042
2    0.345458  0.881023  0.960155
3    0.515800  0.352888  0.682026
4    0.804506  0.447780  0.305676
..        ...       ...       ...
329  0.348268  0.512512  0.546789
330  0.854548  0.317432  0.124896
331  0.520955  0.116990  0.939516
332  0.730676  0.107655  0.209220
333  0.141618  0.557154  0.581961

[334 rows x 3 columns]

In [70]:
newdf.loc[:, ['B']]

            B
0    0.135993
1    0.056516
2    0.345458
3    0.515800
4    0.804506
..        ...
329  0.348268
330  0.854548
331  0.520955
332  0.730676
333  0.141618

[334 rows x 1 columns]

In [71]:
newdf.head()

          B         C         D
0  0.135993  0.451597  0.546875
1  0.056516  0.881566  0.529042
2  0.345458  0.881023  0.960155
3  0.515800  0.352888  0.682026
4  0.804506  0.447780  0.305676

In [72]:
df = pd.DataFrame({'Name': ['Alice', 'Bob', 'Aritra'],
                   'Age': [25, 30, 35],
                   'Location': ['Seattle', 'New York', 'Kona']},
                  index=([10, 20, 30]))

In [73]:
df.head()

      Name  Age  Location
10   Alice   25   Seattle
20     Bob   30  New York
30  Aritra   35      Kona

In [74]:
df.dropna(how = 'any', axis=1)

      Name  Age  Location
10   Alice   25   Seattle
20     Bob   30  New York
30  Aritra   35      Kona

In [75]:
df.drop_duplicates(subset = ['Name'])

      Name  Age  Location
10   Alice   25   Seattle
20     Bob   30  New York
30  Aritra   35      Kona

In [76]:
df.shape

(3, 3)

In [77]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, 10 to 30
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      3 non-null      object
 1   Age       3 non-null      int64
 2   Location  3 non-null      object
dtypes: int64(1), object(2)
memory usage: 96.0+ bytes

In [78]:
df['Name'].value_counts(dropna=False)

Name
Alice     1
Bob       1
Aritra    1
Name: count, dtype: int64

In [79]:
df['Age'].value_counts(dropna=True)

Age
25    1
30    1
35    1
Name: count, dtype: int64

In [80]:
df['Location'].value_counts(dropna=False)

Location
Seattle     1
New York    1
Kona        1
Name: count, dtype: int64

In [81]:
df.isnull()

     Name    Age  Location
10  False  False     False
20  False  False     False
30  False  False     False